name: honest_guide
description: © Václav Pisinger | Vytvořeno jakožto ročníková práce na Gymnáziu Čelíkovice. Uvedeno jako oficiální projekt k šíření kultury dvojměstí Brandýsa nad Labem - Stará Boleslavi. 
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  equatable: ^2.0.5
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  flutter_polyline_points: ^2.0.0
  location: ^6.0.1
  url_launcher: ^6.2.5
  flutter_launcher_icons: ^0.13.1
  google_maps_flutter: ^2.5.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^12.0.0
  flutter_cache_manager: ^3.3.1
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1
  awesome_notifications: ^0.9.2
  timezone: ^0.9.2
  rxdart: ^0.27.7
  permission_handler: ^11.3.0
  icons_flutter: ^0.0.4
  webview_flutter: ^4.7.0
  flutter_tts: ^4.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/logo.jpg"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/img/welcome.jpg
  - assets/data/culture_data.json
  - assets/data/nature_data.json
  - assets/data/food_data.json
  - assets/data/event_data.json
  - assets/img/logo.png
  - assets/img/ckl.png
  - assets/img/mapilu.jpeg
  - assets/img/vapi.jpeg
  - assets/img/logoTB.png
  - assets/img/centerznaklogotyp.png
  - assets/img/bnlsbILU1.png
  - assets/img/bnlsbILU2.png
  - assets/img/bnlsbILU3.png
  - assets/img/bnlsbILU4.png
  - assets/img/bnlsbILU5.png
  - assets/img/KNPM.jpg
  - assets/img/ŽH.jpg
  - assets/img/SV.jpg
  - assets/img/NSVP.jpg
  - assets/img/NFH.jpg
  - assets/img/zbnl.jpg
  - assets/img/fb.png
  - assets/img/yt.png


  fonts:
  - family: BB-UttaraGrotesk
    fonts:
    - asset: assets/fonts/BB-UttaraGrotesk-Title.ttf
      weight: 600
    - asset: assets/fonts/BB-UttaraGrotesk-Regular.ttf
      weight: 200
    - asset: assets/fonts/BB-UttaraGrotesk-Semibold.ttf
      weight: 400